### PR TITLE
easy production of maven artifact, bump to api 19, and cleanup.

### PR DESCRIPTION
**Pull request by rhodey**
bumped to api version 19, modified build.gradle for easy production of maven artifact, removed ic_launcher drawables and some other redundant or unused elements from the library project.

### CODE REVIEW

**Comment by passsy** [comment]
already done in development branch

I should merge it :/

**Comment by rhodey** [comment]
@passsy thanks for getting back to me so quick :)

right now HoloCircularProgressBar is included by source in our [project](https://github.com/WhisperSystems/Flock) and I'd really like to use a maven artifact instead. I could package and publish my own artifact but packing other's code is weird so I'd much rather just help authors out with publishing.

**Comment by passsy** [comment]
I'm currently merging the development branch. I'll publish to maven afterwards. I've never done this before so give me some time reading docs and so forth :wink:

**Comment by rhodey** [comment]
glad to hear :D good luck!

**Comment by passsy** [comment]
merge done but the maven thing has to wait some days

**Comment by rhodey** [comment]
no worries, looking forward to it!

**Pull request closed without merging**
