### PR TITLE
Gradle support. Fixes  passsy/android-HoloCircularProgressBar#5

### PR DESCRIPTION
**Pull request by ghost**
This gradle files may need some adjustments, but library builds OK. Haven't tested sample.

### CODE REVIEW

**Comment by passsy** [comment]
I'll migrate this project to Android Studio this weekend. Thanks for the pull request!

**Comment by ubuntudroid** [comment]
@passsy any news on migration to gradle/Android Studio?

**Comment by passsy** [comment]
sry not yet. I'm struggling with a good structure. I'm not sure if I should drop the Eclipse support.
The quick start with the sample project is harder with Android Studio. 
I need to test a bit more.

**Comment by ghost** [comment]
@passsy I think you can include both Eclipse and Android Studio support at the same time without interferences

**Comment by sailorseashell** [comment]
OH man I would love to see gradle support for this lib and see it uploaded to the central maven repository for easy inclusion in projects.

**Comment by passsy** [comment]
I had to create a new pull request because some improvements where needed. see https://github.com/passsy/android-HoloCircularProgressBar/pull/25

I will close this PR and merge the other

**Pull request closed without merging**
